### ISSUE TITLE
Crash when open the menu

### ISSUE THREAD

**Issue by Fastc0de** [Kopamed/Raven-bPLUS#89]
**Describe the bug**
Error when opening the menu

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Version of Raven [1.1.0] 

**Additional context**
It happens that when I enter the game and give rshift to open the menu, it crashes. I have deleted everything and reinstalled the forge together with version 1.8.9 but it keeps happening and I don't have any mod apart from the raven and I don't have any texture packs so I guess it's not an incompatibility either. I don't know what the error could be, but I'll leave what the console left me to see if you could help me please

[11:36:67] [Client thread/ERROR]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.TickEvent$ClientTickEvent@579351d1:
java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.Native
	at net.arikia.dev.drpc.DiscordRPC$DLL.<clinit>(DiscordRPC.java:226)
	at net.arikia.dev.drpc.DiscordRPC.discordShutdown(DiscordRPC.java:84)
	at keystrokesmod.discordRPC.DiscordRPCManager.updateRPCMode(DiscordRPCManager.java:29)
	at keystrokesmod.module.modules.other.DiscordRPCModule.guiUpdate(DiscordRPCModule.java:88)
	at keystrokesmod.main.Ravenbplus.onTick(Ravenbplus.java:162)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_6_Ravenbplus_onTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:336)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2151)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

[11:36:77] [Client thread/ERROR]: Index: 1 Listeners:
[11:36:77] [Client thread/ERROR]: 0: NORMAL
[11:36:77] [Client thread/ERROR]: 1: ASM: keystrokesmod.main.Ravenbplus@2b0df4ba onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[11:36:27] [Client thread/INFO]: Applying holder lookups
[11:36:27] [Client thread/INFO]: Holder lookups applied
[11:36:98] [Client thread/FATAL]: Unreported exception thrown!
java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.Native
	at net.arikia.dev.drpc.DiscordRPC$DLL.<clinit>(DiscordRPC.java:226)
	at net.arikia.dev.drpc.DiscordRPC.discordShutdown(DiscordRPC.java:84)
	at keystrokesmod.discordRPC.DiscordRPCManager.updateRPCMode(DiscordRPCManager.java:29)
	at keystrokesmod.module.modules.other.DiscordRPCModule.guiUpdate(DiscordRPCModule.java:88)
	at keystrokesmod.main.Ravenbplus.onTick(Ravenbplus.java:162)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_6_Ravenbplus_onTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:336)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2151)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

[11:36:98] [Client thread/INFO]: [net.minecraft.init.Bootstrap:func_179870_a:529]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  TLSkinCapeHookLoader (tlskincape1.8.9-1.4.jar)
  FMLLoadingPlugin ([1.8.9] BetterKeystrokes V-1.1.0.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 30/01/22 11:36
Description: Unexpected error

java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.Native
	at net.arikia.dev.drpc.DiscordRPC$DLL.<clinit>(DiscordRPC.java:226)
	at net.arikia.dev.drpc.DiscordRPC.discordShutdown(DiscordRPC.java:84)
	at keystrokesmod.discordRPC.DiscordRPCManager.updateRPCMode(DiscordRPCManager.java:29)
	at keystrokesmod.module.modules.other.DiscordRPCModule.guiUpdate(DiscordRPCModule.java:88)
	at keystrokesmod.main.Ravenbplus.onTick(Ravenbplus.java:162)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_6_Ravenbplus_onTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:336)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2151)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.arikia.dev.drpc.DiscordRPC$DLL.<clinit>(DiscordRPC.java:226)
	at net.arikia.dev.drpc.DiscordRPC.discordShutdown(DiscordRPC.java:84)
	at keystrokesmod.discordRPC.DiscordRPCManager.updateRPCMode(DiscordRPCManager.java:29)
	at keystrokesmod.module.modules.other.DiscordRPCModule.guiUpdate(DiscordRPCModule.java:88)
	at keystrokesmod.main.Ravenbplus.onTick(Ravenbplus.java:162)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_6_Ravenbplus_onTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:336)

**Comment by Nukemo** [comment]
Try turning off DiscordRPC it seems like it's causing the problem through the default config file (default.bplus) which is present in .minecraft/keystrokes/configs/

**Comment by 182exe** [comment]
Try also deleting configs in 'me' folder.
