### ISSUE TITLE
compiled from sources crash

### ISSUE THREAD

**Issue by Nqwsqw** [Kopamed/Raven-bPLUS#92]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  FMLLoadingPlugin ([1.8.9] BetterKeystrokes V-1.1.0.jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 2/3/22 12:20 AM
Description: Exception in server tick loop

java.lang.VerifyError: get long/double overflows locals
Exception Details:
  Location:
    net/minecraft/entity/player/EntityPlayer.func_71059_n(Lnet/minecraft/entity/Entity;)V @320: dload
  Reason:
    Local index 10 is invalid
  Bytecode:
    0x0000000: 2a2b b806 6a9a 0004 b12b b606 6d99 0560
    0x0000010: 2b2a b606 709a 0558 2ab2 0126 b601 38b9
    0x0000020: 02de 0100 9045 0b46 2bc1 0004 9900 152a
    0x0000030: b601 e12b c000 04b6 0674 b806 7846 a700
    0x0000040: 0e2a b601 e1b2 067e b806 7846 2a13 043b
    0x0000050: b606 8138 0424 1302 1717 0417 046a 1302
    0x0000060: fd6a 626a 4525 1704 6a46 2ab6 01ed 240b
    0x0000070: 959d 0009 250b 959e 04f6 1704 1306 8295
    0x0000080: 9e00 0704 a700 0403 3605 0336 0603 3607
    0x0000090: 0336 0803 3609 1509 2ab8 0685 6036 092a
    0x00000a0: b602 d899 002e 1505 9900 292a b401 8301
    0x00000b0: c000 022a b401 c62a b401 d62a b401 d3b2
    0x00000c0: 0688 2ab6 024e 0c0c b602 5284 0901 0436
    0x00000d0: 0615 0599 003d 2ab4 068b 0b95 9e00 342a
    0x00000e0: b401 799a 002d 2ab6 068e 9a00 262a b606
    0x00000f0: 919a 001f 2ab2 0694 b604 839a 0015 2ab6
    0x0000100: 01a7 9a00 0e2b c100 0499 0007 04a7 0004
    0x0000110: 0336 0715 0799 000e 2ab6 02d8 9a00 0704
    0x0000120: a700 0403 3607 1507 9900 0924 1306 956a
    0x0000130: 4524 2562 452b b806 9a2a b401 7999 002a
    0x0000140: 180a 2ab6 069d 8d98 9c00 1f2a b205 ccb6
    0x0000150: 065e 3a0c 190c c600 1119 0cb6 0405 c106
    0x0000160: 9f99 0006 0436 080b 380c 0336 0d2a b806
    0x0000170: a236 0e2b c100 0499 0020 2bc0 0004 b606
    0x0000180: a338 0c15 0e9e 0012 2bb6 06a4 9a00 0b04
    0x0000190: 360d 2b04 b606 a72b b406 a839 0f2b b406
    0x00001a0: a939 112b b406 aa39 132b 2ab8 06ae 24b6
    0x00001b0: 06af 3615 1515 9903 8e15 099e 0082 2bc1
    0x00001c0: 0004 9900 2e2b c000 042a 1509 8613 043b
    0x00001d0: 6a2a b402 7313 0378 6ab8 037f 8d2a b402
    0x00001e0: 7313 0378 6ab8 037c 768d b606 b3a7 0033
    0x00001f0: 2b2a b402 7313 0378 6ab8 037f 7615 0986
    0x0000200: 6a13 043b 6a8d 1406 b42a b402 7313 0378
    0x0000210: 6ab8 037c 1509 866a 1304 3b6a 8db6 06b8
    0x0000220: 2a59 b402 e414 06b9 6bb5 02e4 2a59 b402
    0x0000230: e714 06b9 6bb5 02e7 2a03 b606 bd15 0899
    0x0000240: 00ab 2ab4 0183 1204 2bb6 0303 0f14 0209
    0x0000250: 0fb6 030b b606 c1b9 06c2 0100 3a16 1916
    0x0000260: b903 bf01 0099 0061 1916 b903 c301 00c0
    0x0000270: 0004 3a17 1917 2aa5 004c 1917 2ba5 0046
    0x0000280: 2a19 17b6 06c5 9a00 3d2a 1917 b606 c914
    0x0000290: 06ca 989c 0030 1917 2a13 02f9 2ab4 0273
    0x00002a0: 1303 786a b803 7f8d 2ab4 0273 1303 786a
    0x00002b0: b803 7c76 8db6 06b3 1917 2ab8 06ae 0cb6
    0x00002c0: 0597 57a7 ff9b 2ab4 0183 01c0 0002 2ab4
    0x00002d0: 01c6 2ab4 01d6 2ab4 01d3 b206 ce2a b602
    0x00002e0: 4e0c 0cb6 0252 2ab6 06d1 2bc1 06d3 9900
    0x00002f0: 332b b406 d699 002c 2bc0 06d3 b406 dabb
    0x0000300: 06dc 592b b706 ddb6 06e3 2b03 b506 d62b
    0x0000310: 180f b506 a82b 1811 b506 a92b 1813 b506
    0x0000320: aa15 0799 0028 2ab4 0183 01c0 0002 2ab4
    0x0000330: 01c6 2ab4 01d6 2ab4 01d3 b206 e62a b602
    0x0000340: 4e0c 0cb6 0252 2a2b b606 e915 079a 0050
    0x0000350: 1508 9a00 4b15 0599 0026 2ab4 0183 01c0
    0x0000360: 0002 2ab4 01c6 2ab4 01d6 2ab4 01d3 b206
    0x0000370: ec2a b602 4e0c 0cb6 0252 a700 232a b401
    0x0000380: 8301 c000 022a b401 c62a b401 d62a b401
    0x0000390: d3b2 06ef 2ab6 024e 0c0c b602 5225 0b95
    0x00003a0: 9e00 082a 2bb6 06f2 2ab4 0183 b400 ef9a
    0x00003b0: 008a 2bc1 0002 9900 832b c000 023a 162a
    0x00003c0: b601 e13a 1719 16b6 06f5 9900 0b19 16b6
    0x00003d0: 06f8 a700 0401 3a18 1917 c600 5f19 18c6
    0x00003e0: 005a 1917 b604 05c1 06fa 9900 4f19 18b6
    0x00003f0: 0405 b205 b6a6 0044 1306 fb2a b804 7986
    0x0000400: 1306 fc6a 6238 1915 0699 000b 1719 1306
    0x0000410: fd62 3819 2ab4 0435 b604 3a17 1996 9c00
    0x0000420: 1b19 16b6 0700 b205 b610 64b6 0703 2ab4
    0x0000430: 0183 1916 101e b607 0724 1307 0895 9b00
    0x0000440: 0a2a b207 0eb6 01b6 2a2b b607 112b c100
    0x0000450: 0499 000b 2bc0 0004 2ab8 0715 2a2b b807
    0x0000460: 182a b601 e13a 162b 3a17 2bc1 071a 9900
    0x0000470: 1b2b c007 1ab4 071e 3a18 1918 c100 0499
    0x0000480: 000a 1918 c000 043a 1719 16c6 0032 1917
    0x0000490: c100 0499 002a 1916 1917 c000 042a b607
    0x00004a0: 2219 16b4 040e 9d00 172a b205 cc01 c001
    0x00004b0: e3b6 0657 2a19 16b2 05cc b805 c62b c100
    0x00004c0: 0499 0079 170c 2bc0 0004 b606 a366 3818
    0x00004d0: 2ab2 0725 1718 1306 136a b806 16b6 0452
    0x00004e0: 150e 9e00 0b2b 150e 0768 b606 a72a b401
    0x00004f0: 83c1 0727 9900 4617 180d 959e 003f 1718
    0x0000500: 8d14 0103 6b8e 3619 2ab4 0183 c007 27b2
    0x0000510: 072d 2bb4 072e 2bb4 072f 2bb4 0730 1304
    0x0000520: 3b6a 8d63 2bb4 0731 1519 1406 b40e 1406
    0x0000530: b414 0732 03bc 0ab6 0737 2a13 0440 b606
    0x0000540: 04a7 002c 2ab4 0183 01c0 0002 2ab4 01c6
    0x0000550: 2ab4 01d6 2ab4 01d3 b207 3a2a b602 4e0c
    0x0000560: 0cb6 0252 150d 9900 072b b607 3bb1     
  Stackmap Table:
    same_frame(@9)
    append_frame(@65,Float,Float)
    same_frame(@76)
    append_frame(@122,Float)
    same_frame(@135)
    same_locals_1_stack_item_frame(@136,Integer)
    full_frame(@209,{Object[#2],Object[#767],Float,Float,Float,Integer,Integer,Integer,Integer,Integer},{})
    same_frame(@272)
    same_locals_1_stack_item_frame(@273,Integer)
    same_frame(@291)
    same_locals_1_stack_item_frame(@292,Integer)
    same_frame(@305)
    same_frame(@359)
    full_frame(@407,{Object[#2],Object[#767],Float,Float,Float,Integer,Integer,Integer,Integer,Integer,Top,Top,Float,Integer,Integer},{})
    full_frame(@496,{Object[#2],Object[#767],Float,Float,Float,Integer,Integer,Integer,Integer,Integer,Top,Top,Float,Integer,Integer,Double,Double,Double,Integer},{})
    same_frame(@544)
    same_frame(@573)
    append_frame(@606,Object[#956])
    append_frame(@707,Object[#4])
    chop_frame(@710,1)
    chop_frame(@746,1)
    same_frame(@801)
    same_frame(@843)
    same_frame(@893)
    same_frame(@925)
    same_frame(@936)
    append_frame(@981,Object[#2],Object[#483])
    same_locals_1_stack_item_frame(@982,Object[#483])
    append_frame(@1044,Object[#483],Float)
    full_frame(@1081,{Object[#2],Object[#767],Float,Float,Float,Integer,Integer,Integer,Integer,Integer,Top,Top,Float,Integer,Integer,Double,Double,Double,Integer},{})
    same_frame(@1096)
    same_frame(@1116)
    append_frame(@1161,Object[#483],Object[#767])
    same_frame(@1213)
    append_frame(@1261,Float)
    chop_frame(@1338,1)
    chop_frame(@1348,2)
    full_frame(@1389,{Object[#2],Object[#767]},{})

	at net.minecraft.server.management.PlayerList.func_148545_a(PlayerList.java:457)
	at net.minecraft.server.network.NetHandlerLoginServer.func_147326_c(NetHandlerLoginServer.java:133)
	at net.minecraft.server.network.NetHandlerLoginServer.func_73660_a(NetHandlerLoginServer.java:60)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:730)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:611)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:148)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:469)
	at java.lang.Thread.run(Thread.java:745)

**Comment by Ghoxy1** [comment]
Sad :(
